version: "3.8"

services:
  my-python-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    command: poetry run python src/binance_volatility_manager.py # Replace with your actual Python script
    volumes:
      - .:/opt/app # Mount the current directory into the container's /opt/app
